# Global Digital Advertising Performance Analysis

## 01 - Data Understanding

### Project Overview

The objective of this project is to analyze digital advertising performance across multiple platforms, including Google Ads, Meta Ads, and TikTok Ads. The analysis aims to identify key performance drivers, evaluate campaign efficiency, and generate actionable business insights through data analysis and visualization.

### Objectives

- Understand the dataset structure
- Explore available variables
- Identify data types
- Examine dataset dimensions
- Prepare the data for subsequent analysis

In [1]:
# ==========================
# Import Libraries
# ==========================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.float_format", "{:,.2f}".format)

In [2]:
df = pd.read_csv("../data/global_ads_performance_dataset.csv")

df.head()

,date,platform,campaign_type,industry,country,impressions,clicks,CTR,CPC,ad_spend,conversions,CPA,revenue,ROAS
0,2024-01-21,Google Ads,Search,Fintech,UAE,59886,2113,0.04,1.26,"2,662.38",159,16.74,"4,803.43",1.80
1,2024-01-22,TikTok Ads,Search,EdTech,UK,135608,5220,0.04,1.18,"6,159.60",411,14.99,"64,126.68",10.41
2,2024-06-15,TikTok Ads,Video,Healthcare,USA,92313,5991,0.06,0.85,"5,092.35",267,19.07,"10,489.07",2.06
3,2024-01-02,TikTok Ads,Shopping,SaaS,Germany,83953,5935,0.07,1.32,"7,834.20",296,26.47,"50,505.07",6.45
4,2024-02-22,TikTok Ads,Search,Healthcare,UK,91807,4489,0.05,1.93,"8,663.77",107,80.97,"3,369.53",0.39

#### Dataset Dimensions

In [3]:
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")

Number of rows: 1800
Number of columns: 14

#### Column Names

In [5]:
df.columns

Index(['date', 'platform', 'campaign_type', 'industry', 'country',
       'impressions', 'clicks', 'CTR', 'CPC', 'ad_spend', 'conversions', 'CPA',
       'revenue', 'ROAS'],
      dtype='object')

#### Dataset Information

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1800 entries, 0 to 1799
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           1800 non-null   object
 1   platform       1800 non-null   object
 2   campaign_type  1800 non-null   object
 3   industry       1800 non-null   object
 4   country        1800 non-null   object
 5   impressions    1800 non-null   int64
 6   clicks         1800 non-null   int64
 7   CTR            1800 non-null   float64
 8   CPC            1800 non-null   float64
 9   ad_spend       1800 non-null   float64
 10  conversions    1800 non-null   int64
 11  CPA            1800 non-null   float64
 12  revenue        1800 non-null   float64
 13  ROAS           1800 non-null   float64
dtypes: float64(6), int64(3), object(5)
memory usage: 197.0+ KB

#### Statistical Summary

In [7]:
df.describe()

,impressions,clicks,CTR,CPC,ad_spend,conversions,CPA,revenue,ROAS
count,"1,800.00","1,800.00","1,800.00","1,800.00","1,800.00","1,800.00","1,800.00","1,800.00","1,800.00"
mean,"102,919.02","3,962.68",0.04,1.57,"6,171.53",181.56,46.61,"30,101.85",6.45
std,"55,740.90","2,941.86",0.02,0.80,"5,777.00",171.42,41.19,"34,560.03",6.59
min,"5,059.00",91.00,0.01,0.28,58.00,2.00,4.80,142.69,0.13
25%,"54,948.00","1,678.00",0.03,0.95,"1,966.59",59.00,20.20,"7,275.76",2.17
50%,"103,653.00","3,318.00",0.04,1.46,"4,393.86",130.00,33.38,"18,362.97",4.29
75%,"150,470.25","5,628.00",0.05,2.05,"8,455.83",252.25,56.81,"38,963.39",8.21
max,"199,650.00","16,660.00",0.10,3.95,"38,453.32","1,151.00",335.86,"295,028.26",49.00

#### Initial Observations

This section provides a high-level overview of the dataset contents, including sample records, column types, and the business meaning of each variable.

In [8]:
df.head(10)

,date,platform,campaign_type,industry,country,impressions,clicks,CTR,CPC,ad_spend,conversions,CPA,revenue,ROAS
0,2024-01-21,Google Ads,Search,Fintech,UAE,59886,2113,0.04,1.26,"2,662.38",159,16.74,"4,803.43",1.80
1,2024-01-22,TikTok Ads,Search,EdTech,UK,135608,5220,0.04,1.18,"6,159.60",411,14.99,"64,126.68",10.41
2,2024-06-15,TikTok Ads,Video,Healthcare,USA,92313,5991,0.06,0.85,"5,092.35",267,19.07,"10,489.07",2.06
3,2024-01-02,TikTok Ads,Shopping,SaaS,Germany,83953,5935,0.07,1.32,"7,834.20",296,26.47,"50,505.07",6.45
4,2024-02-22,TikTok Ads,Search,Healthcare,UK,91807,4489,0.05,1.93,"8,663.77",107,80.97,"3,369.53",0.39
5,2024-10-15,TikTok Ads,Search,Fintech,Canada,17666,724,0.04,0.37,267.88,23,11.65,"5,220.85",19.49
6,2024-08-14,Meta Ads,Video,Fintech,USA,118252,3748,0.03,0.42,"1,574.16",152,10.36,"12,838.56",8.16
7,2024-04-05,TikTok Ads,Search,EdTech,UAE,92939,5176,0.06,0.66,"3,416.16",388,8.80,"96,298.69",28.19
8,2024-04-17,Meta Ads,Display,EdTech,Germany,30939,937,0.03,0.59,552.83,63,8.78,"16,531.03",29.90
9,2024-11-13,Google Ads,Shopping,Fintech,USA,8748,362,0.04,1.21,438.02,10,43.80,966.57,2.21

#### Business Meaning of Columns

| Column | Description |
|---|---|
| date | Date of campaign activity |
| platform | Advertising platform used |
| campaign_type | Type of advertising campaign |
| industry | Industry category |
| country | Target country |
| impressions | Number of times ads were shown |
| clicks | Number of ad clicks |
| CTR | Click-through rate |
| CPC | Cost per click |
| ad_spend | Total advertising spend |
| conversions | Number of completed actions |
| CPA | Cost per acquisition |
| revenue | Revenue generated |
| ROAS | Return on ad spend |

In [10]:
df.nunique().sort_values(ascending=False)

ad_spend         1800
revenue          1798
impressions      1790
CPA              1634
clicks           1616
ROAS              999
CTR               624
conversions       518
date              360
CPC               327
country             7
industry            5
campaign_type       4
platform            3
dtype: int64

#### Dataset Overview

The dataset contains advertising campaign performance data collected across multiple digital marketing platforms. Each record represents the performance of a campaign on a specific date and includes engagement, spending, conversion, and revenue metrics.

From the initial exploration, the dataset appears to contain both categorical and numerical variables that will support descriptive, comparative, and performance analysis.

In [11]:
# Separate numerical and categorical columns

numerical_columns = df.select_dtypes(include=["number"]).columns.tolist()
categorical_columns = df.select_dtypes(include=["object"]).columns.tolist()

print("Numerical Columns:")
print(numerical_columns)

print("\nCategorical Columns:")
print(categorical_columns)

Numerical Columns:
['impressions', 'clicks', 'CTR', 'CPC', 'ad_spend', 'conversions', 'CPA', 'revenue', 'ROAS']

Categorical Columns:
['date', 'platform', 'campaign_type', 'industry', 'country']

In [12]:
df.dtypes

date              object
platform          object
campaign_type     object
industry          object
country           object
impressions        int64
clicks             int64
CTR              float64
CPC              float64
ad_spend         float64
conversions        int64
CPA              float64
revenue          float64
ROAS             float64
dtype: object

#### Initial Findings

- The dataset contains both categorical and numerical variables.
- Several metrics such as CTR, CPC, CPA, and ROAS are already calculated.
- The platform variable contains three advertising platforms.
- Campaigns span multiple industries and countries.
- The date column will allow time-series analysis.
- Revenue and advertising spend can be used to evaluate profitability and efficiency.